name = "Axiom Odyssey: New Epoch"
author = "AxiomOdyssey"
version = "0.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70dbcbaab1223b58802c7f8921875e26865c252b6e38a3607667f1f58b9df035"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"

[options]
acceptable-game-versions = ["1.7.10"]
