name = "Axiom Odyssey: New Epoch"
author = "AxiomOdyssey"
version = "0.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e54979ef017c2a68d5dc18c6a97d18e9083b10a6a4aa3153ff27c156bfb01f1a"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"

[options]
acceptable-game-versions = ["1.7.10"]
