name = "Axiom Odyssey: New Epoch"
author = "AxiomOdyssey"
version = "0.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82a0f174be3d88174cfe39471c94ac751045211c4983a05ec7cc40570dc97d60"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"

[options]
acceptable-game-versions = ["1.7.10"]
